version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies....
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - echo Build completed on `date`
      #authenticate aws ECR
      - eho authenticate ECR
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 885102517186.dkr.ecr.eu-central-1.amazonaws.com
      - eho Build docker image start
      - docker build -t dev .
      - docker tag dev:latest 885102517186.dkr.ecr.eu-central-1.amazonaws.com/dev:latest

  post_build:
    commands:
      - echo pushing
      - docker push 885102517186.dkr.ecr.eu-central-1.amazonaws.com/dev:latest
